version: '3.8'

services:
  editor:
    image: sandersl/editor:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/editor'
      - '/editor/node_modules'
    ports:
      - "3000"
    environment:
      - CHOKIDAR_USEPOLLING=true